
=== Github Pages

Github pages offer unlimited *free* web hosting as *public webpages*, hosted and published through GitHub.
It allows a person to serve any *static website* straight from his repository.
GitHub pages support custom domains, one can host a static website on GitHub pages free of cost,
with deploys straight from Git. Companies reportedly use GitHub Pages in their tech stacks, 
including Lyft, Stack, and Tokopedia. 

=== Set-Up

* *Step 1 : Create a repository*
** Head over to GitHub and create a new repository named username.github.io, where username is your username (or organization name) on GitHub.

* *Step 2 : Clone the repository*
** Go to the folder where you want to store your project, and clone the new repository.

* *Step 3 : Build your project*
** Enter the project folder and add an index.html file.

* *Step 4 : Push it*
** Add, commit, and push your changes.

* *Step 5 : Host your webpage*
** Fire up a browser and go to https://username.github.io.

.Related
****
link: https://pages.github.com/
****




