
=== git clone

==== Command

`git clone <remote_repo_url>.git`

Eg: `git clone https://github.com/HarshKapadia2/git_basics.git`

==== Prerequisites

The following terms are required to be understood:

* link:#_aliases[Aliases]
* link:#_repository[Repository (repo)]

==== Description

Clone/copy an entire link:#_repositories_its_types/:~:text=Remote%20repository%20is%20the%20repo%20on%20the%20server[remote repo] into the current folder (to which the git CLI is pointing).

A new folder will be created with the name of the repo. `cd` (change directory) into that folder to start using it.

==== Options/Flags

===== No option

* The entire remote repo will be cloned locally into a new folder with the same name as the remote repo.

===== -b <branch_name> or --branch <branch_name>

* Clone only a specific branch of a remote repo.
* It is useful to fetch the required branch quickly to fix the issues in a big project.
* Eg: `git clone -b master https://github.com/HarshKapadia2/git_basics.git` or `git clone -b master --single-branch https://github.com/HarshKapadia2/git_basics.git`
* `--single-branch` is assumed.

===== --depth <depth_number>

* Shallow clone only upto a certain number of latest commits and history either in a `--single-branch` (assumed) or in all branches (`--no-single-branch`).
* Specify the branch name using `-b` or `--branch` for `--single-branch`. The `master` branch is assumed, if not specified.
* Eg: `git clone -b v2 --depth 1 https://github.com/HarshKapadia2/attendance_manager.git`
* With `--no-single-branch`, use link:#_git_branch[`git branch -a`] to view the fetched branches and link:#_git_switch[`git switch <branch_name>`] to use it.
* Eg: `git clone --no-single-branch --depth 1 https://github.com/HarshKapadia2/attendance_manager.git`

.Related
****
* https://www.ithands.com/blog/advanced-git-features/#:~:text=Cloning%20a%20Specific%20Branch[`-b` reference]
* https://linuxhint.com/git-shallow-clone-and-clone-depth/[Shallow clone reference]
****

'''