=== git clone

==== Command

`git clone <remote_repo_url>.git`

[.word-break-all]
Eg:

* `git clone https://github.com/HarshKapadia2/git_basics.git`
* `git clone ssh://username@hostname:port/absolute/path/to/repo`

==== Prerequisites

The following terms are required to be understood:

* link:#_aliases[Aliases]
* link:#_repository[Repository (repo)]

==== Description

Clone/copy an entire link:#_repositories_its_types[local or a remote repository] into the current directory (to which the CLI is pointing).

A new directory will be created with the name of the repository. `cd` (change directory) into that directory to start using it.

==== Options/Flags

===== No option

* The link:#_default_branch[default branch] of the local or remote repository will be cloned into a new directory with the same name as the repository.

[.word-break-all]
* Cloning a remote repository: `git clone https://github.com/HarshKapadia2/git_basics.git`
* Cloning a local repository: `git clone x:/coding/git/local_repo`

===== -b <branch_name> or --branch <branch_name>

* Clone only a specific branch of a remote repo.
* It is useful to fetch the required branch quickly to fix the issues in a big project.

[.word-break-all]
* Eg: `git clone -b main https://github.com/HarshKapadia2/git_basics.git` or `git clone -b main --single-branch https://github.com/HarshKapadia2/git_basics.git`
* `--single-branch` is assumed.

===== --depth <depth_number>

* **Shallow clone** only upto a certain number of latest commits and history either in a `--single-branch` (default) or in all branches (`--no-single-branch`).
* Specify the branch name using `-b` or `--branch` for `--single-branch`. The `main` (previously called `master`) branch is assumed, if not specified.

[.word-break-all]
* Eg: `git clone -b v2 --depth 1 https://github.com/HarshKapadia2/attendance_manager.git`
* With `--no-single-branch`, use link:#_git_branch[`git branch -a`] to view the fetched branches and link:#_git_switch[`git switch <branch_name>`] to use it.
* Eg: `git clone --no-single-branch --depth 1 https://github.com/HarshKapadia2/attendance_manager.git`

WARNING: link:https://stackoverflow.com/a/28985327/11958552[Shallow clones cannot be pushed to a new repository^]. The shallow clone will either have to be [unshallowed] or the link:https://git.harshkapadia.me/#_the_git_directory[`.git` directory^] will have to be deleted (start afresh by link:#_git_init[initializing a new repository]).

.Related
****
* link:https://www.ithands.com/blog/advanced-git-features/#:~:text=Cloning%20a%20Specific%20Branch[`-b` reference^]
* link:https://linuxhint.com/git-shallow-clone-and-clone-depth[Shallow clone reference^]
****

'''
