
=== git checkout

==== Command

`git checkout <flags> <options>`

==== Prerequisites

The following terms are required to be understood:

* link:#_head[HEAD]
* link:#_branches[Branches]

==== Description

The git checkout command operates upon three distinct entities: files, commits, and branches.

The git checkout command lets you navigate between the branches created by link:#_git_branch[`git branch`].

Further details https://www.atlassian.com/git/tutorials/using-branches/git-checkout[here].

==== Options/Flags

===== <new_branch_name>

* Switches to / views / checks out a branch with the name `new_branch_name`.
* Eg: `git checkout feature_branch`

NOTE: link:#_git_switch[`git switch`] can also be used to achieve the same result.

===== -b <new_branch_name>

* Creates a new branch & checks it out (switches to it) as well.

NOTE: The new branch is created from the curent HEAD.

===== -b <new_branch_name> <existing_branch_name>

* Creates a new branch & checks it out (switches to it) as well.

NOTE: The new branch is created from the last commit of the `existing_branch_name`.

===== <commit's_SHA>

* You can checkout a specific commit.

NOTE: This condition will land you in a link:#_head[detached HEAD] state.

===== <file_name.ext>

* To replace a modified file in the working directory/copy with the added/committed state version of that file.
* If there are no staged changes, then the copy of the file in the local link:#_repository[repository] is used, otherwise the current file is overwritten by the staged copy of the file.

NOTE: link:#_git_restore[`git restore`] can also be used to achieve the same result.

.Related
****
* link:#_git_merge[git merge]
* link:#_git_branch[git branch]
* link:#_git_restore[git restore]
* link:#_git_switch[git switch]
****

'''