
=== git branch

==== Command

`git branch <flags> <options>`

==== Prerequisites

The following term is required to be understood:

* link:#_branches[Branches]

==== Description

The `git branch` command lets the user create, list, rename and delete branches.

It doesn’t let the user switch between branches or put a forked history back together again. For this reason, git branch is tightly integrated with the link:#_git_checkout[`git checkout`] and link:#_git_merge[`git merge`] commands.

https://www.atlassian.com/git/tutorials/using-branches[Further details].

==== Options/Flags

===== --list or <no_option>

* List all of the local branches in the local link:#_repository[repository].

===== -a

* Lists all, ie, local and fetched remote branches.

===== <branch_name>

* Creates a new branch, but this does not check out the new branch.
* Use link:#_git_checkout[`git checkout`] to check out (view/switch to) the new branch.

===== -d <branch_name>

* Delete the specified branch.

TIP: If the currently checked out branch is to be deleted, link:#_git_checkout[switch to a different branch] and then run the above command.

NOTE: This is a safe operation as Git prevents the deletion of the branch if it has unmerged changes.

===== -D <branch_name>

* Force delete the specified branch, even if it has unmerged changes.

TIP: If the currently checked out branch is to be deleted, link:#_git_checkout[switch to a different branch] and then run the above command.

===== -m <new_branch_name>

* Rename the current branch to `new_branch_name`.

.Related
****
* link:#_git_merge[git merge]
* link:#_git_checkout[git checkout]
****

'''