
=== git status

==== Commands

`git status`

==== Prerequisites

The following terms are required to be understood:

* link:#_untracked_files[Untracked files]
* link:#_added_files[Added files]
* link:#_modified_files[Modified files]
* link:#_staging_staging_areaindex[Staging (staging area/index)]
* link:#_working_tree[Working tree]

==== Description

* Run this command at any time to display the current status of the working directory.
* This command shows two things: 
    ** The files in your Working Tree (untracked and modified files)
    ** The files in your Staging Area (added files)

==== Options/Flags

===== -s or --short

* Gives a summary of untracked and staged (added) files.
* Meanings of different symbols
    ** `??` implies untracked files.
    ** `A` implies newly staged files.
    ** `M (red)` implies modifications in a staged file that has not been staged again.
    ** `M (green)` implies modifications in a staged file that has been staged again.
    ** `MM (green and red)` implies modifications in a file that has been staged with modifications, but not yet committed.
    ** `D (red)` implies the deletion of a staged file that has not been staged again.
    ** `D (green)` implies the deletion of a staged file that has been staged again.
    ** `R (green)` implies the renaming/moving/both of a file that has been staged again.

NOTE: Once a file is renamed, moved or both renamed and moved, it is marked as deleted (red coloured `D`) by Git and a new untracked file (red coloured `??`) is shown in its place when `git status -s` is run. Once the link:#_git_add[`git add`] command is run, Git realises that the file has been renamed/moved/both and displays a green coloured `R` when `git status -s` is run again.

'''