
=== .gitignore file

* .gitignore is a file which tells git which files (or patterns) in the directory it should ignore. 
* It's usually used to avoid committing transient files from the working directory/copy (a copy of the most recent state of the files you're working on) that aren't useful to other collaborators, such as compilation products, temporary files that IDEs create, etc.

==== Syntax

* Comments start with `#`.
* Ignored file names to be written in the format `file_name.ext`. eg: `test.txt`
* `*.ext` ignores all files with the extension `.ext`.
* If a file is in a directory, use `dir_name/file_name.ext`.
* A resource for .gitignore file templates for different programming languages: https://github.com/github/gitignore

===== Ignore files without modifying `.gitignore`

* You can ignore a file/folder only for your local repository without modifying `.gitignore` by adding a pattern in `.git/info/exclude`.
* The syntax is the same as for `.gitignore`.
* This is useful if you want to keep a local `TODO` list, but don't want to commit it to the repository, and don't want to modify `.gitignore` for everyone.

.Related
****
* link:index.html#_git_add[git add]
****

'''