
=== Unstage Files Staged/Added by Mistake

A lot of times files are added/staged by mistake, no matter whether they are new or modified. The solution below will unstage all the files that were staged by mistake.

==== Prerequisites

* link:#_added_files[Added/staged files]
* link:#_staging_staging_areaindex[Staging]

==== Solution

NOTE: The commands below will simply unstage added files and will NOT result in data loss.

* General syntax: `git reset HEAD \-- "<files/folders/patterns>"`

* Files

	** For a single file, use `git reset HEAD \-- "<file_name.ext>"`.

	** For multiple files, use `git reset HEAD \-- "<file_1.ext>" "<file_2.ext>"...`.

	** For files with the same extension, use `git reset HEAD \-- "<*.ext>"`.

* Directories/folders

	** For a single directory, use `git reset HEAD \-- "<path/to/dir>"`.

	** For multiple directories, use `git reset HEAD \-- "<path/to/dir_1>" "<path/to/dir_2>"...`.

* To unstage everything in the staging area, use `git reset HEAD` or `git reset HEAD \-- *`.

'''
