
=== Unstage Files Staged/Added by Mistake

A lot of times files are added/staged by mistake, no matter whether they are new or modified. The solution below will unstage all the files that were staged by mistake.

==== Prerequisites

* link:#_added_files[Added/staged files]
* link:#_staging_staging_areaindex[Staging]

==== Solution

* General syntax `git reset HEAD \-- "<files/folders/patterns>"`.

* To unstage all added/staged files, use `git reset HEAD` or `git reset HEAD \-- *`.

* For files

	** To unstage added/staged files, use `git reset HEAD \-- "<file_name.ext>"`.

	** To unstage multiple added/staged files, use `git reset HEAD \-- "<file_1.ext>" "<file_2.ext>"...`.

	** To unstage all added/staged files with the same extension, use `git reset HEAD \-- "<*.ext>"`.

* For directories/folders

	** To unstage a/an staged/added directory, use `git reset HEAD \-- "<path/to/dir>"`.

	** To unstage multiple staged/added directories, use `git reset HEAD \-- "<path/to/dir_1>" "<path/to/dir_2>"...`.

'''
