= git_basics
Harsh Kapadia
v2
:favicon:   ./static/img/favicon.ico
:toc:       left
:icons:     font
:imagesdir: ./static/img
:docinfo:   shared
:author:    Harsh Kapadia

== Abstract

A web site for the basics of Git and GitHub-like services.

== Preface

The open source community is inclusive and friendly. Contributing to it is always exciting if done in the spirit of improving the community and enjoying oneself.

Knowing the basics of Git and GitHub is the only prerequisite to start contributing and learning them sometimes feels like a daunting task. The aim of this guide is to help anyone get started with open source and keep helping them along their journey.

*This project is open source* and the repository can be found at https://github.com/HarshKapadia2/git_basics[role=external,window=_blank]. Contributions to keep it updated and error-free are appreciated and issues and pull requests are most welcome!

For further questions, please feel free to contact the author, Harsh Kapadia, via https://otc.zulipchat.com[OTC^], https://twitter.com/harshgkapadia[Twitter^], https://www.linkedin.com/in/harshgkapadia/[LinkedIn^] or e-mail (harshgkapadia@gmail.com).

[IMPORTANT]
====
* https://www.youtube.com/watch?v=HF12-91iazM[Git and GitHub crash course^]
* https://www.youtube.com/watch?v=uJdFNksgKJA[Hacktoberfest, Open Source and Pull Requests^]
====

NOTE: One might want to familiarize themselves with some link:#_terms[Git terms] before starting, although they will be linked at places where they are required as well.

NOTE: GitHub is gradually renaming the default branch of repositories from `master` to `main`. The default branch name for new repositories is now `main`. Existing repositories are not impacted by this change. Later this year, one will be able to rename the default branch for existing repositories. For more details, check the https://github.com/github/renaming[renaming repo^] by GitHub.

== General #1

include::./refs/general_1.adoc[]

== Commands

include::./refs/commands.adoc[]

== General #2

include::./refs/general_2.adoc[]

== GitHub

include::./refs/github_1.adoc[]

== Making a Repository Contributor Friendly

include::./refs/contributor_friendly_repo.adoc[]

== Terms

include::./refs/terms.adoc[]

== Misc

include::./refs/misc.adoc[]

'''

[quote, Selena Gomez]
Kindness always wins.

[quote, Robert Ingersoll]
We rise by lifting others.

[quote, Helen Keller]
Alone, we can do so little;
Together we can do so much.

++++
	<div class="pwa-install-div hidden">
		<div id="pwa-install-text">Ready for offline use!</div>
		<button id="pwa-install-btn">Install</button>
		<button id="pwa-install-dismiss">
			<img src="static/img/clear_cross.svg" alt="X">
		</button>
	</div>
++++
