= git_basics
Harsh Kapadia
v2
:favicon:   ./static/img/favicon.ico
:toc:       left
:imagesdir: ./static/img
:icons:     image
:iconsdir:	./static/img/admonition_icons
:docinfo:   shared
:author:    Harsh Kapadia
:sectanchors:
:figure-caption!:

== Abstract

A web site for the basics of Git and GitHub-like services.

== Preface

The open source community is inclusive and friendly. Contributing to it is always exciting if done in the spirit of improving the community and enjoying oneself.

Knowing the basics of Git and GitHub is the only prerequisite to start contributing and learning them sometimes feels like a daunting task. The aim of this guide is to help anyone get started with open source and keep helping them along their journey.

*This project is open source* and the repository can be found at https://github.com/HarshKapadia2/git_basics[role=external,window=_blank]. Contributions to keep it updated and error-free are appreciated and issues and pull requests are most welcome!

For further questions, please feel free to contact the author, Harsh Kapadia, via https://otc.zulipchat.com[OTC^], https://twitter.com/harshgkapadia[Twitter^], https://www.linkedin.com/in/harshgkapadia/[LinkedIn^] or e-mail (harshgkapadia@gmail.com).

[IMPORTANT]
====
Get started with Git and GitHub:

* https://www.youtube.com/watch?v=HF12-91iazM[Git and GitHub crash course^]
* https://www.youtube.com/watch?v=uJdFNksgKJA[Hacktoberfest, Open Source and Pull Requests^]
====

NOTE: One might want to familiarize themselves with some link:#_terms[terms] before starting, although they will be linked at places where they are required as well.

[NOTE#_main_vs_master_1]
====
'main' vs 'master' #1:

* This only applies to GitHub link:#_repositories[repositories].
* GitHub is gradually renaming the link:#_default_branch[default branch] of repositories from 'master' to 'main'.
* The name of the default branch for new repositories on GitHub is now 'main'.
* Existing repositories on GitHub are not impacted by this change, but they can now rename their branches if they wish to.
* For more details, please check the https://github.com/github/renaming[renaming repo^] by GitHub.
* link:#_change_default_branch_name[Changing the default branch of the local Git client] is also possible.
* link:#_main_vs_master_2['main' vs 'master' #2]
====

== General #1

include::./refs/general_1.adoc[]

== Commands

include::./refs/commands.adoc[]

== General #2

include::./refs/general_2.adoc[]

== Correcting Common Mistakes

include::./refs/correcting_common_mistakes.adoc[]

== Git Internals

include::./refs/git_internals.adoc[]

== GitHub

include::./refs/github_1.adoc[]

== Contributor Friendly Repository

include::./refs/contributor_friendly_repo.adoc[]

== Terms

include::./refs/terms.adoc[]

== Misc

include::./refs/misc.adoc[]

'''

[quote, Selena Gomez]
Kindness always wins.

[quote, Robert Ingersoll]
We rise by lifting others.

[quote, Helen Keller]
Alone, we can do so little;
Together we can do so much.

++++
	<a href="./static/html/privacy_policy.html">Privacy policy</a>

	<div class="pwa-install-div hidden">
		<div id="pwa-install-text">Ready for offline use!</div>
		<button id="pwa-install-btn">Install</button>
		<button id="pwa-install-dismiss" aria-label="Dismiss PWA install prompt">
			<img src="static/img/clear_cross.svg" alt="X">
		</button>
	</div>

	<button class="btn hidden back-to-top-btn" aria-label="Scroll to top"><img src="static/img/up-arrow.svg" alt="Top"></button>
++++
